production:
    host: ec2-54-243-193-227.compute-1.amazonaws.com
    adapter: postgresql
    encoding: unicode
    database: d6f2cjh5r0q19
    port: 5432
    pool: 5
    username: sbjalcwccmwtly
    password: 76b7af32132cfcc1e22bcac38c95c5308ec7efea3144f3aee423e783fdfcb80b

development:
    adapter: postgresql
    encoding: unicode
    database: habbits
    pool: 5
    username: willfelix
    password: ninjadev

test:
    adapter: postgresql
    encoding: unicode
    database: habbits
    pool: 5
    username: willfelix
    password: ninjadev
