# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b279f3cf62c0962636d9010792c1c8167155d6efa7759bf290d859746c28c04809e017fe90e7ec4b633f602f8a62321bd5d9b81557bed56bea38e2eb4d7f2317

test:
  secret_key_base: 7f91fc7ed413f49ae9a5869eca283396b846fbae080f1bcb4133a4901f3b8e4e2c0bfaf7e4ef0d562efbb871f9118b448fd44ceaeb2c37586d519f6e687c008e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
